### ISSUE TITLE
Certain aggregate symbols cause problems in other aggregates

### ISSUE THREAD

**Issue by ben-reilly** [increpare/PuzzleScript#203]
Somewhat similar to #202 (and by extension, #128), special symbols seem to not be parsed properly when used in an aggregate.
e.g.

```
* = Crate
@ = * and Target
```

gives the error

```
Something bad's happening in the LEGEND
```

**Comment by increpare** [comment]
need to do #375 first - the system right now can't handle chains of definitions, so even if I allow the compiler to parse this it will get confused.

**Comment by increpare** [comment]
So I thought about this, and I managed to implement support for it that didn't break the tests. However, I feel like it's not something I want to support? The small but definite chance of this change randomly breaking someone's game isn't maybe worth allowing people to code in a coding style I'm not too hot for - the randomo symbols are enabled chiefly for the map editor. I just see lots of nasty edge cases coming up if I add this feature and anyone actually uses it. So better that people encounter errors sooner rather than later ^^ (but a better error message may be nice)

(
the change involved introducing the following regexps in key places:
    var reg_name_simple = /[\p{L}\p{N}_]+[\p{Z}\s]*/u;///\w*[a-uw-zA-UW-Z0-9_]/;
    var reg_name = /((?![(])[\p{L}\p{N}\p{P}\p{S}])+[\p{Z}\s]*/u;///\w*[a-uw-zA-UW-Z0-9_]/;
    var reg_name_nocomma = /((?![(,])[\p{L}\p{N}\p{P}\p{S}])+[\p{Z}\s]*/u;///\w*[a-uw-zA-UW-Z0-9_]/;

![image](https://user-images.githubusercontent.com/465632/127540396-5117add1-934c-46fd-af66-b2acdb351156.png)

)
