### ISSUE TITLE
Level gets messed up after modifying CollisionLayers

### ISSUE THREAD

**Issue by ncrecc** [increpare/PuzzleScript#321]
The tiles seem to randomly turn into other ones once a new layer is added, or an old one deleted. This does not effect the code itself and goes away once re-loading the level.
![](http://image.prntscr.com/image/482343c8ac4642bcbbcd9a9034a9b1fc.png)
In addition to that, after I tried to press right in the game, the entire page froze and I couldn't save.

**Comment by increpare** [comment]
This is when you hit rebuild rather than run I assume? Yeah, this is a
known thing. It does its best to reload things without corrupting, and it
could do better, but there'll always be weird cases I think.  I have no
immediate plans to fix this

(Unfortunate that it froze. That shouldn't happen. If you can repro it and
send me some code as a separate bug report, that'd be useful)

**Comment by increpare** [comment]
(thanks for the report!)

**Comment by increpare** [comment]
I'm closing this, assuming the answer is "yes". If it's not, let me know and I'll reopen it.
