### ISSUE TITLE
|, [, and ] should be considered keywords

### ISSUE THREAD

**Issue by ncrecc** [increpare/PuzzleScript#338]
```
title Simple Block Pushing Game
author Stephen Lavelle
homepage www.puzzlescript.net

========
OBJECTS
========

Background
LIGHTGREEN GREEN
11111
01111
11101
11111
10111

Player
Black Orange White Blue
.000.
.111.
22222
.333.
.3.3.

LeftBracket
White
...00
...0.
...0.
...0.
...00

RightBracket
White
00...
.0...
.0...
.0...
00...

VerticalBar
Gray
..0..
..0..
..0..
..0..
..0..

Caret
Gray
..0..
.0.0.
.....
.....
.....

=======
LEGEND
=======

. = Background
P = Player
[ = LeftBracket
] = RightBracket
| = VerticalBar
^ = Caret

=======
SOUNDS
=======

================
COLLISIONLAYERS
================

Background
Player
LeftBracket
RightBracket
VerticalBar
Caret

======
RULES
======

[P | ] [] -> [no ]]

==============
WINCONDITIONS
==============

=======
LEVELS
=======



```

When compiling,  ^ is warned against for being a keyword, but nothing is said about |, [, or ] despite the rules being unreadable due to them.

**Comment by increpare** [comment]
Hi, thanks for the bug report!

Did you run into this as a confusing bug in practice, or is it a notional
bug that wasn't actually a problem for you?

Either way, it's fair enough. I guess I should only be a warning if they're
used ambiguously in the rules section - because they're useful in the map
editor.  So [ should be ok, even though it's confusing to see, and typing
"no |" should be ok as well.  It's dangerous to give unnecessary warnings
because people then can ignore warnings.

best,

S

**Comment by ncrecc** [comment]
Hi, this wasn't really a problem for me, mostly just found it because I was bored and decided to see what would happen if I actually tried it out. Definitely a minor issue.
