### ISSUE TITLE
verbose_logging fails on last rule, with "late" and "run_rules_on_level_start"

### ISSUE THREAD

**Issue by darkrecher** [increpare/PuzzleScript#357]
Suppose we have 3 late rules, that may each apply twice on level start.

The verbose_logging will tell the 2 first rules apply "x2", but the last rule applies only once. 

The bug does not occur on not-late rules.

It never occurs on the next turns, executed after each player move.

The direction is not releveant. The bug may occur on all-directions rules, bi-directions rules and mono-direction rules.

Here is a proof of the bug :

http://www.puzzlescript.net/editor.html?hack=05c60ecb3dd6ada53eec6de59aca9eb7

**Comment by increpare** [comment]
Huh, so the problem is that it's not getting logged, but it is getting
applied, right? spooky bug! thanks for catching it (and for the nice
example!) - it shouldn't be too hard to fix - I'm working on a fork of
puzzlescript right now, so I may not fix it for a while.

Is it causing you problems right now? If it is, I'll get on it and fix it
sooner :)

**Comment by darkrecher** [comment]
Thank you for your answer.

Yes, everything applies well. But the log is uncomplete.

It does not cause any problem to me. I just finished the game I wanted to code (Atomix demake). And anyway, it is not critical.
