### ISSUE TITLE
movement not getting correctly cleared from tile - 

### ISSUE THREAD

**Issue by ThatScar** [increpare/PuzzleScript#492]
movement, replacement, switching irrelevent rule presence, adding stationary, removing stationary, rotating the rules around 180 degrees
idk what I'm saying but I am losing my mind over this weird thing and it is wrong and I am right
https://www.puzzlescript.net/editor.html?hack=06eff735286c417633dbd7b33ff9d1a7

I've actually found a solution to remedy it (the commented rule that is just rotated around 180 degrees) but not the cause so I'll leave this hell for you to solve.

**Comment by ThatScar** [comment]
Another test: https://www.puzzlescript.net/editor.html?hack=592d54f2f4197208d69d1052acfa0af0

**Comment by increpare** [comment]
What should I do when I open it? 
What's the expected behaviour? 
What's the observed behaviour?

**Comment by ThatScar** [comment]
Apologies.
In the initial link I've sent, there are 2 running rules and one rule commented out, which I will call "alternative rule 2".
If you run the game and move left or right, you will notice the player moves by two tiles. The level is set up for the exactly one move, please always restart after doing it.
If rule 2 is swapped out with alternative rule 2, the player will only move by one tile even though rule 2 and alternative rule 2 should do the exact same thing.
If you comment out rule 1, it will always move by one tile regardless of which rule 2 variant is used.
Additionally, if you put "stationary" on the right side of rule 2, it will also make it always move by one tile regardless of anything I've said previously.

Expected behaviour: both rule 2 variants should work exactly the same. Player should move by one tile.

**Comment by increpare** [comment]
did a further simplified version of it - definitely an engine bug - good catch

https://www.puzzlescript.net/editor.html?hack=897b4569b11c462e5c7819f5a6a311a8
(if you move right you skip ahead two tiles rather than one)

rule 65 is getting applied twice, which is bad.  As you noticed, changing "[ > Player | ] -> [ Crate | Player ]" explicitly to "[ > Player | ] -> [ Crate | stationary Player ]" fixes the problem, I think because the bug is that a movement isn't correctly getting cleared from that tile.  

shouldn't be too awful to fix :)

**Comment by ThatScar** [comment]
Ran into this issue again today. This time, it wasn't the same object but 2 different objects and when one tried to jump onto the other, it transferred the movement somehow.
Admittedly, having 2 objects on the same layer enter the same tile is my fault but hey, a bug is a bug.
https://www.puzzlescript.net/editor.html?hack=f34019d7f50c9167f158c95cf72e1274
To observe it, press any movement/action keys until objects reach the second corner.
In code is a comments on where the buggy line is and then comments on how to circumvent it.

P.S. Can I somehow rename the issue? Honestly, I kind of wish to rewrite it altogether, because at first this was a complete mess.

**Comment by increpare** [comment]
further simplified example
https://www.puzzlescript.net/editor.html?hack=8aedd0e21382af305b27f947c0c74d95
(if you move right you skip ahead two tiles rather than one)

**Comment by sftrabbit** [comment]
Just for the sake of documentation, here's an example of something that changes behaviour due to this fix. The new behaviour makes more sense, IMO - just was an unexpected break on something I'm working on.

```
startloop
[ > Crate | ] -> [ > Crate | Temp ]
[ > Crate | STATIONARY Temp ] -> [ > Crate | ACTION Temp ]
endloop
```

Before this fix, the loop would run only once because when it tries to apply the first rule on the second iteration it has no effect. After this fix, that rule creates a new `Temp` that is `STATIONARY` and so you end up in an infinite loop.

Easy to deal with though - in this particular case, changing the first line to `[ > Crate | NO Temp ] -> [ > Crate | Temp ]` would work, or otherwise using some other marker to make sure you don't replace the existing `ACTION Temp`.

**Comment by increpare** [comment]
@sftrabbit Thanks for letting me know - it's good to have a sense for how many games are getting broken by the occasional semantics-changing things like this.  Apologies for the disruption; glad you found a workaround yourself.  :)
