### ISSUE TITLE
Feature request: add a "once" keyword

### ISSUE THREAD

**Issue by Draknek** [increpare/PuzzleScript#503]
As discussed earlier, this would behave like "random" except it would apply the first rule that matches rather than a random rule.

Reasoning: some games want to be deterministic, but need a rule to only be applied once to get the correct behaviour.

**Comment by increpare** [comment]
Okay, having let it slosh about in the old brain tubes for a bit, I feel that this is too niche, given that there's already 'random', and if you want deterministic once-ness you can hack it by adding a unique object to the scene.  I think this covers all possible use-cases.  The down-side is the additional complexity caused by adding new keywords - of learning and of maintenance.  The case for ease of understanding is not so clearly for or against the proposal - it's one extra thing to learn, but seeing 'random' in code where people the intent is 'once' can be confusing.

I might reopen at some point in the future, but I want to put it to rest for now.

Anyway, thanks for the suggestion!
