### ISSUE TITLE
some message features

### ISSUE THREAD

**Issue by minotalen** [increpare/PuzzleScript#523]
- embed sprites in messages
`message Push [Crate] onto [Target]!`
This should make messages a lot more versatile. (some players might even produce their own fonts!)

- line break with \\
`message HOW TO PLAY:\\Push [Crate] onto [Target]!`

- text alignment in prelude
`text_align left`

- ctrl+click to load message (for previewing)

**Comment by increpare** [comment]
Suggestions 1 is *super* cute but also maybe too extravagant.  A thing about messages is that I don't want them to be that versatile, I want them to be a kind of bare-bones feature, because using text to communicate things isn't playing to the engine's strengths (if that makes sense?).

Suggestion 4 is sensible (but really low priority)

2 and 3 give too fine-grained control.  Because of fixed console size you can do line breaks if you really want but if you have to go out of your way to do it and I'm ok with that.

**Comment by minotalen** [comment]
I have done manual line breaks in the past, those are kinda tedious but oh well. If it's not broken don't fix it they say, and that makes sense.

Not sure what you mean about 'playing to the engines strengths'? Are you of the opinion that mechanisms and rules should solely be conveyed/discovered through clever level design?

Anyway, thanks for taking the ideas into account :)
