### ISSUE TITLE
Include movements being cancelled because they're against the border in verbose_logging

### ISSUE THREAD

**Issue by ncrecc** [increpare/PuzzleScript#531]
Might help out some newbies trying to interact with the border who don't understand what's going on

**Comment by increpare** [comment]
I had a think about this, and here's my conclusion (apologies for the pause):

It feels like something you'd add given that there's already some way of indicating what movements not at the border are getting canceled, or some other way of debugging/visualisation movement, which isn't the case (yet).  So I'm going to close this because it's a really marginal suggestion, at the margins of a feature that doesn't exist yet.  However it's a good suggestion - thanks for suggesting it!
