### ISSUE TITLE
size of 's' isn't regenerated when you open editor after resizing?

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#704]
![image](https://user-images.githubusercontent.com/465632/128510261-43f65fef-787e-4910-8e60-4caf3b539cc0.png)

(think this is solved in clementsparrow's branch IIRC)

**Comment by ClementSparrow** [comment]
I changed the rendering system A LOT, I'm not sure looking at my branch will help you solve that. If you say that because you've seen that I wrote code specifically for the S, it was to deal with another issue, caused by the fact that I can have sprites of any size, and that defines the size of the legend glyphs, but the S is at a fixed 5x5 size.
