### ISSUE TITLE
loop through demo directory on tests (from clementsparrow)

### ISSUE THREAD

**Issue by increpare** [increpare/PuzzleScript#748]
cf https://github.com/ClementSparrow/Pattern-Script/commit/5b8d35c283bfc22257bada8e8bc42cb51f75b9d7

**Comment by ClementSparrow** [comment]
note that I use a file that lists all the demos because it cannot be done in javascript. But since you have a server for puzzlescript.net you could have a script running there and serving the file. Also, since you have the gallery database with (I guess) the gists of the games, you could directly pull the game gists from the gallery.

**Comment by increpare** [comment]
OTOH I manually added all the gallery games already once.  Which I had forgotten about makes this task obsolete.   (i don't want to have the test suite reliant on downloading stuff from online).  ^^

**Comment by increpare** [comment]
>note that I use a file that lists all the demos because it cannot be done in javascript
Suggestion: would you want to regenerate it in compile.js?

**Comment by ClementSparrow** [comment]
I'd like to avoid using compile.js at all :-) And if I want to regenerate the file when I add a demo, "ls demo/ > tests/demo_list.txt" seems far superior to me than anything node.js could provide :-D
