### ISSUE TITLE
Infinite restart loop is possible

### ISSUE THREAD

**Issue by ClementSparrow** [increpare/PuzzleScript#774]
If `run_rules_on_level_start` is set in the preamble, there is a possibility that a rule triggers a `restart` command and causes an infinite loop. That was the matter of #341 that has been fixed by ignoring the `restart`. However, this fix missed another edge case: if a rule triggers a command `again`, and then, after againing, another rule triggers a command `restart`, there will still be an infinite loop.

Here is an example: [restart_infinite.txt](https://github.com/increpare/PuzzleScript/files/7031156/restart_infinite.txt). Command `again` is used to make the player move toward a target, and `restart` is triggered when the player reaches the target. You can see the infinite loop in the first level. (Pressing R and U also does strange things, here.) The second level shows an example where the player starts directly on a target, which would cause an infinite loop if it had not been fixed by #341.

**Comment by increpare** [comment]
#341 iirc was regarded as a bug because it crashed the editor - in this case the behaviour is the same as if it were an endlessly looping again-based animation, right.  It doesn't lock the editor or the player (you can still quit to the menu).  And I'm not sure how else I'd have it behave, if it is to be regarded as a bug. Hmm.  I'm inclined to think it's ok as-is?
