### ISSUE TITLE
Several test cases have syntax errors -- should this not be fixed?

### ISSUE THREAD

**Issue by david-pfx** [increpare/PuzzleScript#937]
gallery: censored version of NSFW game pornography for beginners -- sprite not square
gallery: Rose --  again] instead of ] again
gallery: The Flames -- extra ")"
-- and so on -- full list available

**Comment by increpare** [comment]
>should this not be fixed?
It's all by design.

These games had various syntax errors back before the compiler was properly checking for syntax errors.  I want the compiler to be able to still cope with these problems, because I don't want my updates to break games that were previously working that people are using the puzzlescript.net runtime for.

**Comment by david-pfx** [comment]
But this does developers of new games a disservice -- you don't find their errors, so they don't get to correct their mistakes

At least all the syntax errors I am finding should be labelled as warnings, even if you don't make them fatal to the compile.

**Comment by increpare** [comment]
>At least all the syntax errors I am finding should be labelled as warnings, even if you don't make them fatal to the compile.

I checked both Pornography and Rose and both get lots of warnings generated when you load in the editor ( I don't want to expose these messages to the end-players so I hide warnings in the player).   If you find errors that aren't generating warnings in the editor, please let me know.
